version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  backend-nginx:
    image: nginx:1.25
    ports:
      - '8081:80'
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
