# Generated by Django 5.1.2 on 2025-06-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=50, verbose_name='Номер транспорта')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправки')),
                ('arrival_time', models.DateTimeField(verbose_name='Время доставки')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Дистанция (км)')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='deliveries/', verbose_name='Медиафайл')),
                ('tech_state', models.CharField(choices=[('ok', 'Исправно'), ('broken', 'Неисправно')], default='ok', max_length=10, verbose_name='Техническое состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.cargotype', verbose_name='Тип груза')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.packagetype', verbose_name='Тип упаковки')),
                ('services', models.ManyToManyField(to='references.service', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.deliverystatus', verbose_name='Статус доставки')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.transportmodel', verbose_name='Модель транспорта')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-created_at'],
            },
        ),
    ]
